
drop table ADMIN cascade constraints;
drop table ADDRESS cascade constraints;
drop table APPLICATION cascade constraints;


-------------------------             EK_ADMIN        ----------------------------------------
CREATE TABLE ADMIN(
	EMAIL_ID VARCHAR2(50),
	NAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(70) NOT NULL,
	PHONE_NUMBER VARCHAR2(10) NOT NULL UNIQUE,
	constraint ADMIN_EMAIL_ID_PK primary key ( EMAIL_ID )
);
-------------------------             EK_ADMIN_ADDRESS        ----------------------------------------
CREATE TABLE ADDRESS (
	ADDRESS_ID NUMBER(8)  NOT NULL,
	STREET_ADDRESS_1 VARCHAR2 (500) NOT NULL,
	STREET_ADDRESS_2 VARCHAR2 (500),
	CITY VARCHAR2(50) NOT NULL,
	STATE VARCHAR2(50) NOT NULL,
	ZIP VARCHAR2(50) NOT NULL,
	COUNTRY VARCHAR2(50) NOT NULL,
    APPLICATION_ID NUMBER(10),
    EMAIL_ID VARCHAR2(50),
	constraint ADDRESS_ADDRESS_ID_PK primary key ( ADDRESS_ID )
);

CREATE TABLE APPLICATION (
	APPLICATION_ID NUMBER(8) NOT NULL, 
	APPLICATION_FOR VARCHAR (50) NOT NULL,
	CLASS_NAME VARCHAR(2) NOT NULL,
	MOTOR_CYCLE VARCHAR(5) NOT NULL,
	APPLICATION_TYPE VARCHAR (50) NOT NULL,
	SUFFIX VARCHAR (50) NOT NULL,
	LAST_NAME VARCHAR (50) NOT NULL,
	FIRST_NAME VARCHAR (50) NOT NULL,
	MIDDLE_NAME VARCHAR (50) NOT NULL,
	BIRTH_SURNAME VARCHAR (50) NOT NULL,
	SSN VARCHAR (50) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	SEX VARCHAR (50) NOT NULL,
	HEIGHT NUMBER (10) NOT NULL,
	WEIGHT NUMBER (10) NOT NULL,
	EYE_COLOR VARCHAR (50) NOT NULL,
	HAIR_COLOR VARCHAR (50) NOT NULL,
	RACE VARCHAR (50) NOT NULL,
	ETHNICITY VARCHAR (50) NOT NULL,
	PLACE_OF_BIRTH VARCHAR (50) NOT NULL,
	FATHERS_LAST_NAME VARCHAR (50) NOT NULL,
	MOTHERS_MIDDLE_NAME VARCHAR (50) NOT NULL,
	PHONE_NO NUMBER(10) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SIGNATURE VARCHAR(50) NOT NULL,
	DATE_OF_SIGNATURE DATE NOT NULL,
	APPROVED BOOLEAN NOT NULL,
	constraint APPLICATION_APPLICATION_ID_PK primary key ( APPLICATION_ID )
	
)

-------------------------             FOR EK_ADMIN_ADDRESS TABLE        ----------------------------------------
ALTER TABLE ADDRESS ADD CONSTRAINT APPLICATION_APPL_ID_FK FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID);
ALTER TABLE ADDRESS ADD CONSTRAINT ADMIN_ADRS_EMAIL_FK FOREIGN KEY ( EMAIL_ID ) REFERENCES ADMIN( EMAIL_ID );

-------------------------             EK_ADMIN
INSERT INTO ADMIN (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('tom@infosys.com', 'Tom', 'f11c799502ed788b70e2130749cf17d1263720aaa1513f28c2acf9c5230cc702', '7886189067');
--Password: Tom@123
INSERT INTO ADMIN (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('harry@infosys.com', 'Harry', 'harry123', '7687156584');
--Password: Harry@123

-------------------------             EK_ADMIN_ADDRESS
INSERT INTO ADDRESS (ADDRESS_ID, STREET_ADDRESS_1, STREET_ADDRESS_2, CITY, STATE, ZIP, COUNTRY, APPLICATION_ID, EMAIL_ID) VALUES (5000, 'Ist Main, Building No.3', 'Park Square', 'Los Angeles', 'California', '752110', 'United States', NULL, 'tom@infosys.com');
INSERT INTO ADDRESS (ADDRESS_ID, STREET_ADDRESS_1, STREET_ADDRESS_2, CITY, STATE, ZIP, COUNTRY, APPLICATION_ID, EMAIL_ID) VALUES (5001, '4th Main, Building No.8', 'Mountain Springs', 'Las Vegas', 'Nevada', '859122', 'United States', NULL, 'tom@infosys.com');
INSERT INTO ADDRESS (ADDRESS_ID, STREET_ADDRESS_1, STREET_ADDRESS_2, CITY, STATE, ZIP, COUNTRY, APPLICATION_ID,  EMAIL_ID) VALUES (5002,  '8th Main, Floor no-7, Building No.2', 'Midtown Manhattan', 'New York City', 'New York', '755123','United States', NULL, 'harry@infosys.com');
INSERT INTO ADDRESS (ADDRESS_ID, STREET_ADDRESS_1, STREET_ADDRESS_2, CITY, STATE, ZIP, COUNTRY, APPLICATION_ID, EMAIL_ID) VALUES (5003, '2nd Main, Floor no-8, Building No.13', 'Mid-City', 'New Orleans', 'Louisiana', '760103', 'United States', NULL, 'harry@infosys.com');

select * from ADMIN;
select * from APPLICATION;
--commit;